# Generated by Django 6.0.3 on 2026-04-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='doneeeee',
        ),
    ]
