# Generated by Django 6.0.3 on 2026-04-11 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0003_rename_doneeeee_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('order', models.SmallIntegerField()),
                ('series_data', models.JSONField(default=list)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_blocks', to='gym_tracker.exercise')),
            ],
            options={
                'ordering': ['routine', 'day_number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GymStandardExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_videos', to='gym_tracker.exercise')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_exercise_videos', to='gym_tracker.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_name', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='gym_tracker.gym')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym_tracker.exercise')),
                ('video', models.URLField(blank=True, null=True)),
            ],
            bases=('gym_tracker.exercise',),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(blank=True, help_text='Muscle of the exercise', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym_tracker.muscle'),
        ),
    ]
