# Generated by Django 6.0.3 on 2026-04-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0004_exercise_exerciseblock_gym_gymstandardexercisevideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='person',
            field=models.ForeignKey(limit_choices_to={'role': 'PERSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='gym_tracker.routine'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='gym',
            field=models.ForeignKey(blank=True, help_text='Gym where the custom exercise belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to='gym_tracker.gym'),
        ),
        migrations.AddConstraint(
            model_name='gymstandardexercisevideo',
            constraint=models.UniqueConstraint(fields=('gym', 'exercise'), name='unique_gym_standard_exercise_video'),
        ),
    ]
