# Generated by Django 6.0.3 on 2026-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_tracker", "0005_routine_person_routine_staff_exerciseblock_routine_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exerciseblock",
            constraint=models.UniqueConstraint(
                fields=("routine", "day_number", "order"),
                name="unique_routine_day_order_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciseblock",
            constraint=models.CheckConstraint(
                condition=models.Q(day_number__gte=1),
                name="exerciseblock_day_number_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciseblock",
            constraint=models.CheckConstraint(
                condition=models.Q(order__gte=1),
                name="exerciseblock_order_gte_1",
            ),
        ),
    ]
