# Generated by Django 6.0.3 on 2026-04-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0006_exerciseblock_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
