# Generated by Django 6.0.3 on 2026-09-29 17:13

import gym_tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0008_routine_roles_per_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseblock',
            name='series_data',
            field=models.JSONField(blank=True, default=list, validators=[gym_tracker.validators.validate_series_data]),
        ),
    ]
