# Generated by Django 6.0.3 on 2026-09-29 17:16

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def check_existing_data(apps, schema_editor):
    """Frena la migración con un mensaje claro si hay datos que no cumplen las nuevas reglas."""
    CustomExercise = apps.get_model('gym_tracker', 'CustomExercise')
    Gym = apps.get_model('gym_tracker', 'Gym')
    Muscle = apps.get_model('gym_tracker', 'Muscle')

    problems = []

    orphans = list(CustomExercise.objects.filter(gym__isnull=True).values_list('pk', flat=True))
    if orphans:
        problems.append(f"ejercicios propios sin gimnasio (ids {orphans}): asignales un gimnasio o borralos")

    for model, field in [(Gym, 'name'), (Muscle, 'muscle_name')]:
        duplicated = list(
            model.objects.annotate(key=Lower(field)).values('key')
            .annotate(total=Count('pk')).filter(total__gt=1).values_list('key', flat=True)
        )
        if duplicated:
            problems.append(f"{model.__name__} con nombres repetidos {duplicated}: renombralos")

    if problems:
        raise RuntimeError("No se puede migrar gym_tracker.0010. Hay " + "; ".join(problems) + ".")


class Migration(migrations.Migration):

    dependencies = [
        ('gym_tracker', '0009_exerciseblock_series_data_validation'),
    ]

    operations = [
        migrations.RunPython(check_existing_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customexercise',
            name='gym',
            field=models.ForeignKey(help_text='Gym where the custom exercise belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to='gym_tracker.gym'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(blank=True, help_text='Muscle of the exercise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='gym_tracker.muscle'),
        ),
        migrations.AlterField(
            model_name='exerciseblock',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercise_blocks', to='gym_tracker.exercise'),
        ),
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_gym_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='muscle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('muscle_name'), name='unique_muscle_name_ci'),
        ),
    ]
